FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y \
    git \
    curl \
    docker.io \
    openjdk-17-jdk

USER jenkins
RUN jenkins-plugin-cli --plugins "kubernetes git github workflow-aggregator pipeline-stage-view sonar sonar-quality-gates"
EXPOSE 8080

